# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  FORMATTED_DATE: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
pool:
  vmImage: ubuntu-latest

steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: echo $(Build.SourceVersion)
    displayName: 'Show current commit hash'
  - task: GithubRelease@1
    displayName: 'Attempt to make a github release'
    inputs:
      gitHubConnection: github-test-connection
      repositoryName: milesdai/ci-test
      action: 'create'
      tagSource: 'userSpecifiedTag'
      tag: 'snapshot-$(FORMATTED_DATE)'
      releaseNotesSource: 'inline'
      releaseNotesInline: '[Release notes here]'
      assets: '$(Build.SourcesDirectory)/test/*'

